# Site settings
title:       Sandors Systems Scribbles
email:       sandor@sandorsscribbl.es
author:      Sandor
description: "Sandors HowTo notes to keep the Argo purring."
baseurl:     "http://sandorsscribbl.es"
url:         "http://sandorsscribbl.es"
date_format: "%b %-d, %Y"
sitemap: sitemap.xml

# Google analytics
google_analytics: UA-38590178-1

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username:  e30chris
twitter_username:  e30chris
bitbucket_username:
stackoverflow_id:
google_plus_id:
linkedin_username: chris325i
bitcoin_url: https://onename.io/chrisl
stackoverflow_id:
angellist_username:
medium_id:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
